import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provided from "@/store/Provided";
import Header from "@/components/Header";

const inter = Inter({ subsets: ['latin'], weight: '400'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-full overflow-hidden bg-purple-100 flex flex-col items-center">
          <Provided>
            <Header />
            <main className="w-full flex-1 overflow-y-auto overflow-x-hidden">
            {children}
            </main>
          </Provided>
        </div>
      </body>
    </html>
  );
}
